### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by augustogoncalves** [Autodesk-Forge/forge-bim360.asset.exchange.excel#1]
Adjust license: copyright to Autodesk
Add description and live url (if applicable)
Badges: is Assets really v1&v2? and relationships v2?
User Case, (1), the link to video is broken

Before moving to Autodesk-Forge, please fix https://github.com/xiaodongliang/forge-bim360.asset.exchange.excel on readme and app.json

**Comment by xiaodongliang** [comment]
Thank you Augusto!
Adjust license: copyright to Autodesk  - -- **fixed**
Add description and live url (if applicable)  --**fixed**
Badges: is Assets really v1&v2? and relationships v2?  --

 _because some assets API were updated to v2 (those batch endpoints), the sample uses v1 of previous endpoints, while batch endpoints with v2. As to relationship API, it has been updated to v2 already when releasing._

User Case, (1), the link to video is broken -- **fixed**

Before moving to Autodesk-Forge, please fix https://github.com/xiaodongliang/forge-bim360.asset.exchange.excel on readme and app.json  -**fixed**

Will update documents link when they are available finally.
